<div id="nav-secondary"> 
            <!-- Customer nav --> 
            <a href="#customer" data-toggle="collapse" class="collapsed">
             <h4>Customer</h4> 
            </a> 
            <!-- Nested nav-->
            <div id="customer" class="collapse">
              <ul>
                <li> <a href="#"> Customer </a> </li>
                <li> <a href="#"> Owner/Lessee </a> </li>
                <li> <a href="#customer"> Co-Owner-Lessee </a> </li>
              </ul>
            </div>
            <hr />
            <!-- End Customer nav--> 
            <!-- Car --> 
            <a href="#vehicle" data-toggle="collapse" class="">
            <h4>Vehicle</h4>
            </a>
            <div id="vehicle" class="collapse in single-col">
              <ul>
                <li> <a href="#">Details </a> </li>
                <li> <a href="#"> Insurance </a> </li>
                <li> <a href="#"> Trade-In </a> </li>
              </ul>
            </div>
            <hr />
            <!-- end car --> 
            
            <!-- Finance nav --> 
            <a href="#deal_type" data-toggle="collapse" class="collapsed">
            <h4>Finance</h4>
            </a> 
            <!-- Nested Finance nav-->
            <div id="deal_type" class="collapse" style="height: 0px;">
              <ul>
                <li> <a href="#"> Sales </a> </li>
                <li> <a href="#"> Lienholder </a> </li>
              </ul>
            </div>
            <hr />
            <!-- End Finance nav--> 
            
            <!-- DMV nav --> 
            <a href="#dmv" data-toggle="collapse" class="collapsed">
            <h4>State Info</h4>
            </a> 
            <!-- Nested nav-->
            <div id="dmv" class="collapse" style="height:0px;">
              <ul>
                <li> <a href="#"> Inventory </a> </li>
                <li> <a href="#"> Fees </a> </li>
                <li> <a href="#"> Documents </a> </li>
              </ul>
            </div>
            <hr />
            <!-- End DMV nav--> 
          </div>