<script src="/assets/js/vendor/jquery/jquery.js" type="text/javascript"></script> 
<script src="/assets/js/vendor/jquery/jquery-ui.js" type="text/javascript"></script>
<script src="/assets/js/vendor/bootstrap/bootstrap-dropdown.js" type="text/javascript"></script> 
<script src="/assets/js/vendor/bootstrap/bootstrap-collapse.js" type="text/javascript"></script> 
<script src="/assets/js/vendor/bootstrap/bootstrap-modal.js" type="text/javascript"></script>