<header>
    <div class="container">
      <div class="row">
        <div class="col-xs-4 col-xs-offset-8">
          <div class="site-search">
            <form>
              <input type="text" class="form-control" placeholder="Global Search" />
              <button><i class="fa fa-search"></i></button>
            </form>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-xs-12">
          <nav class="primary">
            <ul id="" class="nav nav-tabs nav-justified">
              <li><a href="#">Home</a></li>
              <li class="active"><a href="#">New Transaction</a></li>
              <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#"> Manage<span class="caret"></span> </a>
                <ul class="dropdown-menu">
                  <li><a href="#">Sub Item</a></li>
                  <li class="dropdown--divider"></li>
                  <li><a href="#">Sub Item</a></li>
                </ul>
              </li>
              <li><a href="#">Reports</a></li>
              <li><a href="#">Utilities</a></li>
            </ul>
          </nav>
        </div>
      </div>
    </div>
  </header>